Traceback (most recent call last):
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
params = dict(
    land_area = 106000,
    total_units = 850,
    acq_price = 200000000 * currency.units,
    far = 2.0,
    start_date= pd.Timestamp('2001-01-01'),
    num_periods = 10,
    period_type = rk.periodicity.Type.YEAR,
    acquisition_cost = -200000000 * currency.units,
    growth_rate = 0.02,
    unit_sales_proj_form=rk.distribution.PERT(
        peak=0.1333,
        weighting=12
        )
    )
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 8[0m
[1;32m      1[0m params [38;5;241m=[39m [38;5;28mdict[39m(
[1;32m      2[0m     land_area [38;5;241m=[39m [38;5;241m106000[39m,
[1;32m      3[0m     total_units [38;5;241m=[39m [38;5;241m850[39m,
[1;32m      4[0m     acq_price [38;5;241m=[39m [38;5;241m200000000[39m [38;5;241m*[39m currency[38;5;241m.[39munits,
[1;32m      5[0m     far [38;5;241m=[39m [38;5;241m2.0[39m,
[1;32m      6[0m     start_date[38;5;241m=[39m pd[38;5;241m.[39mTimestamp([38;5;124m'[39m[38;5;124m2001-01-01[39m[38;5;124m'[39m),
[1;32m      7[0m     num_periods [38;5;241m=[39m [38;5;241m10[39m,
[0;32m----> 8[0m     period_type [38;5;241m=[39m [43mrk[49m[38;5;241;43m.[39;49m[43mperiodicity[49m[38;5;241m.[39mType[38;5;241m.[39mYEAR,
[1;32m      9[0m     acquisition_cost [38;5;241m=[39m [38;5;241m-[39m[38;5;241m200000000[39m [38;5;241m*[39m currency[38;5;241m.[39munits,
[1;32m     10[0m     growth_rate [38;5;241m=[39m [38;5;241m0.02[39m,
[1;32m     11[0m     unit_sales_proj_form[38;5;241m=[39mrk[38;5;241m.[39mdistribution[38;5;241m.[39mPERT(
[1;32m     12[0m         peak[38;5;241m=[39m[38;5;241m0.1333[39m,
[1;32m     13[0m         weighting[38;5;241m=[39m[38;5;241m12[39m
[1;32m     14[0m         )
[1;32m     15[0m     )

[0;31mAttributeError[0m: module 'rangekeeper' has no attribute 'periodicity'

